# Generated by Django 3.0.5 on 2021-08-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('client_basic_profile', 'Basic Profile'), ('client_documents', 'Documents'), ('client_notes', 'Notes'), ('client_insurance', 'Insurance'), ('client_investment', 'Investment'), ('client_cpf', 'CPF'), ('client_srs', 'SRS'), ('client_loans', 'Loans'), ('client_expenditure', 'Expenditure'), ('client_crm_cash_flow', 'CashFlow'), ('client_balance_sheet', 'Balance Sheet'), ('client_coverage_analysis', 'Coverage Analysis'), ('client_customer_limit', 'Customer Limit'), ('client_summary_pdf', 'Summary PDF'), ('client_version_perm', 'Version Change'), ('client_due_premiums', 'Due Premiums'), ('client_maturity_date_perm', 'Maturity Date'), ('client_notes_notification', 'Notes Notification'), ('client_rate_review_date', 'Rate Review Date'), ('client_broadcast', 'BroadCast'), ('client_event', 'Event'), ('client_email_templates', 'Email Templates'), ('client_user_groups', 'Access User Groups'), ('client_tools', 'Access Tools'), ('client_retirement', 'Retirement Calculator'), ('client_calculator_1', 'Basic Retirement Checklist'), ('client_calculator_2', 'Current Network Analysis'), ('client_calculator_3', 'PV Calculator'), ('client_calculator_4', 'FV Calculator'), ('client_calculator_5', 'Retirement Withdrawal'), ('client_mortgage', 'Access Mortgage Calculator'), ('client_todo', 'TODO'), ('client_goals', 'Goals'), ('client_goals_chart', 'Goals Chart'), ('client_aum_chart', 'AUM Chart'), ('client_events_timeline', 'Event Timeline'), ('client_tasks_timeline', 'Task Timeline'), ('client_notes_timeline', 'Notes Timeline'), ('client_activity_timeline', 'Activity Timeline'), ('client_mortgage_timeline', 'Mortgage Timeline')],
            },
        ),
    ]
