# Generated by Django 3.0.5 on 2021-08-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0002_custompermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
