# Generated by Django 3.0.5 on 2021-08-12 09:03

from django.db import migrations
import user_custom.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0004_custompermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=user_custom.models.LowercaseEmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, null=True, unique=True),
        ),
    ]
