# Generated by Django 3.0.5 on 2021-09-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_nationalidimage_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
